spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sys
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver


server:
  port: 8099



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #在映射实体或者属性时,将数据库表中表明和字段名中的下划线去掉,按照驼峰命名法映射

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID